IstalriSkolir/Lakea-Stream-Assistant

Lakea Stream Assistant/ConfigExample.xml
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Models/Configuration/LoadConfig.cs
Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/Singletons/Twitch.cs

- Added Twitch Client to Twitch Singleton
- Added Bot Details to XML
- Added Writing to Chat Functionality

#10 Twitch Write To Chat

---

Lakea Stream Assistant/ConfigExample.xml
Lakea Stream Assistant/Enums/LakeaEnums.cs
Lakea Stream Assistant/EventProcessing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/LakeaFunctions.cs
Lakea Stream Assistant/EventProcessing/TwitchFunctions.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Models/Configuration/EnumConverter.cs
Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/Singletons/Logs.cs
Lakea Stream Assistant/Singletons/OBS.cs
Lakea Stream Assistant/Singletons/Twitch.cs

- Lakea outputs error logs
- Logging level can be configured for different detail levels

#33 Create Error Logs

---

Lakea Stream Assistant/Configurations/ConfigExample.xml
Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Models/Resources/ExternalProcess.cs
Lakea Stream Assistant/Processes/ExternalProcesses.cs
Lakea Stream Assistant/Program.cs

- Lakea can now Exit through console command
- Lakea can start other applications listed in a config file
- Lakea can close other applications that she has started

#41 Start Other Applicaitons

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/EventInput.cs
Lakea Stream Assistant/EventProcessing/TwitchFunctions.cs
Lakea Stream Assistant/Models/Events/TwitchCommand.cs
Lakea Stream Assistant/Models/Events/TwitchSubscription.cs
Lakea Stream Assistant/Singletons/Twitch.cs

- Lakea listens for subscription events
- A default subscription event can be set for all subscriptions

#5 Handle Twitch Subscription

---

Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/TwitchFunctions.cs
Lakea Stream Assistant/Models/Events/EventAbstracts/Event.cs
Lakea Stream Assistant/Models/Events/EventItems/EventItem.cs
Lakea Stream Assistant/Models/Events/LakeaCallback.cs
Lakea Stream Assistant/Models/Events/LakeaCommand.cs
Lakea Stream Assistant/Models/Events/LakeaTimer.cs
Lakea Stream Assistant/Models/Events/TwitchBits.cs
Lakea Stream Assistant/Models/Events/TwitchClientSubscription.cs
Lakea Stream Assistant/Models/Events/TwitchCommand.cs
Lakea Stream Assistant/Models/Events/TwitchFollow.cs
Lakea Stream Assistant/Models/Events/TwitchPubSubSubscription.cs
Lakea Stream Assistant/Models/Events/TwitchRaid.cs
Lakea Stream Assistant/Models/Events/TwitchRedeem.cs
Lakea Stream Assistant/Singletons/Twitch.cs

#90 Subscription Event Not Detected

---

Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/Singletons/OBS.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea will attempt to reconnect to OBS if she becomes disconnected

#85 OBS Disconnections

---

Lakea Stream Assistant/EventProcessing/Commands/DefaultCommands.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/VersionIncrementer.cs
Lakea Stream Assistant/VersionIncrementer.tt

- Added a Shout Out command as a Default Command

#83 Shout Out Command

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleFileParser.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/Processing/EventProcesser.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can send Character Sheet data to Twitch Chat
- Lakea has a Battle Simulator File Parser

#132 Character Sheets

---

Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea checks a Characters level before running the Battle Simulator
- Lakea checks the Battle Simulator exit code after it closes

#138 Battle Simulator Level Check

---

Battle Similator/Enums.cs
Battle Similator/Models/Creatures/Character.cs
Battle Similator/Models/Encounters/Encounter.cs
Battle Similator/Models/Encounters/EncounterResult.cs
Battle Similator/Models/Encounters/MonsterEncounter.cs
Battle Similator/Models/IO.cs
Battle Similator/Models/Training/Training.cs
Battle Similator/Program.cs
Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleFileParser.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/Processing/EventProcesser.cs
Lakea Stream Assistant/VersionIncrementer.cs

- The Battle Simulator now trains characters
- Viewers are informed of when they level up

#124 Character Training

---

Battle Similator/Battle Similator.csproj
Battle Similator/Creatures/Monsters/MonsterGenerator.py
Battle Similator/Creatures/Monsters/UpdateMonsterList.py
Build Scripts/MoveBattleEntities.py

- Building the Battle Simulator now only Copies Creature Files

#141 Battle Simulator Creature Files

---

Battle Similator/Enums.cs
Battle Similator/Models/IO.cs
Battle Similator/Models/Misc/CharacterReset.cs
Battle Similator/Models/Misc/Training.cs
Battle Similator/Program.cs
Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleFileParser.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/Processing/EventProcesser.cs
Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/Singletons/Logs.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Characters can be reset to level 5
- Fixed bug with logging system
- Fixed bug with debugging arguments
- Refactored Lakea's code for handling Battle Simulator events

#134 Battle Simulator Character Reset

---

Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea uses a queuing system for the Battle Simulator

#140 Battle Simulator Queue

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/Processing/EventProcesser.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can send a random twitch chat message from a list

#68 Random Twitch Message

---

Battle Similator/Models/Creatures/Character.cs
Lakea Stream Assistant/Configurations/ConfigExample.xml
Lakea Stream Assistant/VersionIncrementer.cs

- Characters now level up multiple times in one go if they earn enough XP
- Updated ConfigExample.xml

#156 Multiple Level Ups

---

Lakea Stream Assistant/Models/Events/EventStats.cs
Lakea Stream Assistant/Static/Terminal.cs
Lakea Stream Assistant/VersionIncrementer.cs

- The number of Battle Simulator and OBS events are counted
- The number of events are displayed on the terminal

#159 Battle & OBS Events

---

Battle Similator/Models/Creatures/Monster.cs
Battle Similator/Models/NonEncounter/Training.cs

- Tweaked XP gain for characters

#167 Character XP Gain

---

Lakea Stream Assistant/EventProcessing/Processing/TwitchFunctions.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can tell if a subscription was gifted

#145 Gifted Subs

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/LakeaFunctions.cs
Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can now run events on exit

#177 Exit Events

---

Lakea Stream Assistant/EventProcessing/Misc/PythonScripts.cs
Lakea Stream Assistant/Resources/Python/TestPython.py
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can now pass arguments to Python scripts

#180 Python Script Arguments

---

Battle Similator/Models/Resources/HealthBarImage.cs

- The Boss Battle Healthbar has been improved

#179 Boss Healthbar Changes

---

Battle Similator/Models/NonEncounter/Training.cs

- Training is capped to a max of 100XP gained per training session

#194 Character Training

---

Battle Similator/Models/Creatures/Character.cs
Battle Similator/Models/Encounters/BossEncounter.cs
Battle Similator/Models/Encounters/MonsterEncounter.cs
Battle Similator/Models/Resources/IO.cs
Battle Similator/Properties/launchSettings.json
Lakea Stream Assistant/VersionIncrementer.cs

- Characters in monster battles have some stats tracked
- Fixed bug in monster battles stopping the character that killed a boss from getting any XP

#199 Battle Statistics

---

Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea capture events use arguments instead of duration
- Lakea capture events have callbacks

#193 Catch Lakea Duration

---

Battle Similator/Enums.cs
Battle Similator/Models/NonEncounter/UpdateBossHealthbar.cs
Battle Similator/Program.cs
Battle Similator/Properties/launchSettings.json

- Battle Simulator can be ran to just update the bosses healthbar

#239 Boss Battle Healthbar Update

---

Lakea Stream Assistant/EventProcessing/Processing/LakeaFunctions.cs
Lakea Stream Assistant/VersionIncrementer.cs

- One time events have been added via the startup event type
- Known technical debt, will need rewriting once Twitch EventSub has been included

#254 One Time Events

---

Battle Similator/Models/Resources/HealthBarImage.cs
Battle Similator/Properties/launchSettings.json
Lakea Stream Assistant/VersionIncrementer.cs

- Boss Battle profile images get a red cross overlay when the boss is defeated

#262 Boss Battle Profile Crossed Out

---

Lakea Stream Assistant/EventProcessing/Commands/DefaultCommands.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can retrieve the current stream title
- Lakea can Update the stream title
- The title command can be set to mod only

#81 Title Command

---

Lakea Stream Assistant/EventProcessing/Commands/DefaultCommands.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can get the current category
- Lakea can update the current category

#82 Game Command

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/TwitchFunctions.cs
Lakea Stream Assistant/Models/Events/TwitchClientContinuedGiftSubscription.cs
Lakea Stream Assistant/Models/Events/TwitchClientGiftedSubscription.cs
Lakea Stream Assistant/Models/Events/TwitchClientPrimePaidSubscription.cs
Lakea Stream Assistant/Models/Events/TwitchClientResubscriptioncs.cs
Lakea Stream Assistant/Models/Events/TwitchClientSubscription.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Moved Subscriptions from PubSub to Client
- Implemented additional subscription events

#267 Twitch Gifted Subscription

---

Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea will now wait for all exit events to complete before closing

#260 Lakea Exit Events Fixed

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/LakeaEnums.cs
Lakea Stream Assistant/EventProcessing/Misc/ScamMessageDetector.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Lakea can detect banned phrases and scan for scam messages
- Lakea can be configured to take different actions when a scam message is detected

#271 Twitch Scam Bots

---

Battle Similator/Models/Creatures/Character.cs
Battle Similator/Models/Encounters/MonsterEncounter.cs
Battle Similator/Properties/launchSettings.json
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleFileParser.cs
Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/VersionIncrementer.cs

- KO message displays XP lost
- KO messages displays levels lost

#280 Battle Simulator Show XPLevel Loss

---

Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Character statastics command displays character prestige

#287 Chat Prestige Statistics

---

Lakea Stream Assistant/EventProcessing/Commands/QuoteCommand.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Quote command is no longer case sensitive

#292 Quote Command Case Sensitivity Fixed

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Misc/LakeaCaptured.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/Processing/EventPassArguments.cs
Lakea Stream Assistant/EventProcessing/Processing/LakeaFunctions.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Fixed passing arguments bugs from previous refactor work
- Lakea escape ability based on character skill

#296 Lakea Escape Ability

---

Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/EventProcessing/Commands/DefaultCommands.cs
Lakea Stream Assistant/EventProcessing/Commands/QuoteCommand.cs
Lakea Stream Assistant/EventProcessing/Misc/LakeaCaptured.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Refactored new event calls to use static object call
- Fixed quote system

#298 Quote Command Fix

---

Lakea Stream Assistant/EventProcessing/Commands/DefaultCommands.cs
Lakea Stream Assistant/EventProcessing/Commands/ProcessCommand.cs
Lakea Stream Assistant/VersionIncrementer.cs

#297 Process Default Command

---

Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Battle Manager refactored to new data structure

#314 Refactoring Fixes

---

Lakea Stream Assistant/Enums/EnumConverter.cs
Lakea Stream Assistant/Enums/EventEnums.cs
Lakea Stream Assistant/EventProcessing/Commands/DefaultCommands.cs
Lakea Stream Assistant/EventProcessing/Commands/ProcessCommand.cs
Lakea Stream Assistant/EventProcessing/Misc/ExternalProcesses.cs
Lakea Stream Assistant/EventProcessing/Misc/ScamMessageDetector.cs
Lakea Stream Assistant/EventProcessing/Misc/WatchStreakManager.cs
Lakea Stream Assistant/EventProcessing/Processing/EventInput.cs
Lakea Stream Assistant/EventProcessing/Processing/TwitchFunctions.cs
Lakea Stream Assistant/Models/Configuration/Config.cs
Lakea Stream Assistant/Models/Configuration/WatchStreakData.cs
Lakea Stream Assistant/Program.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Moved ExternalProcesses.cs
- Scam Detector can be disabled
- Watch streak system implemented

#302 Stream Watch Streak

---

Lakea Stream Assistant/EventProcessing/Processing/EventPassArguments.cs
Lakea Stream Assistant/Singletons/OBS.cs
Lakea Stream Assistant/VersionIncrementer.cs

- OBS can take and save screenshots

#20 OBS Take Screenshot

---

Lakea Stream Assistant/EventProcessing/Battle Simulator/BattleManager.cs
Lakea Stream Assistant/EventProcessing/Misc/LakeaCaptured.cs
Lakea Stream Assistant/EventProcessing/Processing/EventOutputs.cs
Lakea Stream Assistant/EventProcessing/Processing/EventPassArguments.cs
Lakea Stream Assistant/EventProcessing/Processing/StandardiseInput.cs
Lakea Stream Assistant/EventProcessing/Processing/TwitchFunctions.cs
Lakea Stream Assistant/Singletons/Twitch.cs
Lakea Stream Assistant/VersionIncrementer.cs

- Added ImageFormat argument to OBSSaveScreenshot
- Added RedeemText to Channel Redeem events
- Fixed Watch streak bug
- Refactored some New Event calls

#322 EventHandler New Event
